apply plugin: 'com.android.application'

android {
  namespace 'com.jaredrummler.cyanea.javademo'
  compileSdkVersion buildConfig.compileSdk

  defaultConfig {
    applicationId 'com.jaredrummler.cyanea.javademo'
    minSdkVersion 22
    targetSdkVersion buildConfig.targetSdk
    versionCode 1
    versionName '1.0'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  implementation project(':library')
  implementation deps.material
  implementation deps.androidx.constraintLayout
}
